export const resources = {
  customers: {
    table: "customers",
    orderBy: "id DESC",
    fields: {
      company_name: { type: "string", required: true, maxLength: 150 },
      contact_name: { type: "string", required: true, maxLength: 120 },
      email: { type: "string", maxLength: 160, nullable: true },
      phone: { type: "string", maxLength: 40, nullable: true },
      address: { type: "string", maxLength: 255, nullable: true },
      warehouse_phone: { type: "string", maxLength: 40, nullable: true },
      status: { type: "enum", values: ["active", "inactive"] },
    },
  },
  drivers: {
    table: "drivers",
    orderBy: "id DESC",
    fields: {
      first_name: { type: "string", required: true, maxLength: 100 },
      last_name: { type: "string", required: true, maxLength: 100 },
      phone: { type: "string", required: true, maxLength: 40 },
      email: { type: "string", maxLength: 160, nullable: true },
      license_number: { type: "string", required: true, maxLength: 80 },
      truck_number: { type: "string", maxLength: 80, nullable: true },
      driver_type: { type: "enum", values: ["company", "owner-operator"] },
      status: { type: "enum", values: ["active", "inactive"] },
    },
  },
  ports: {
    table: "ports",
    orderBy: "id DESC",
    fields: {
      code: { type: "string", required: true, maxLength: 40 },
      name: { type: "string", required: true, maxLength: 120 },
      city: { type: "string", required: true, maxLength: 120 },
      contact_phone: { type: "string", maxLength: 40, nullable: true },
      operating_hours: { type: "string", maxLength: 120, nullable: true },
      avg_turn_time: { type: "string", maxLength: 60, nullable: true },
      status: { type: "string", required: true, maxLength: 60 },
    },
  },
  yards: {
    table: "yards",
    orderBy: "id DESC",
    fields: {
      code: { type: "string", required: true, maxLength: 40 },
      name: { type: "string", required: true, maxLength: 120 },
      city: { type: "string", required: true, maxLength: 120 },
      capacity: { type: "string", maxLength: 80, nullable: true },
      utilization: { type: "string", maxLength: 80, nullable: true },
      manager: { type: "string", maxLength: 120, nullable: true },
      status: { type: "string", required: true, maxLength: 60 },
    },
  },
  warehouses: {
    table: "warehouses",
    orderBy: "id DESC",
    fields: {
      code: { type: "string", required: true, maxLength: 40 },
      name: { type: "string", required: true, maxLength: 150 },
      city: { type: "string", required: true, maxLength: 120 },
      address: { type: "string", required: true, maxLength: 255 },
      docks: { type: "string", maxLength: 80, nullable: true },
      contact_phone: { type: "string", maxLength: 40, nullable: true },
      status: { type: "string", required: true, maxLength: 60 },
    },
  },
  containers: {
    table: "containers",
    orderBy: "id DESC",
    fields: {
      customer_id: { type: "number", required: true },
      container_number: { type: "string", required: true, maxLength: 50 },
      container_type: { type: "string", required: true, maxLength: 80 },
      equipment_type: { type: "string", required: true, maxLength: 40 },
      booking_number: { type: "string", maxLength: 80, nullable: true },
      vessel_eta: { type: "string", maxLength: 10, nullable: true },
      size: { type: "string", required: true, maxLength: 20 },
      shipping_line: { type: "string", maxLength: 120, nullable: true },
      pickup_port: { type: "string", required: true, maxLength: 80 },
      pickup_lfd: { type: "string", maxLength: 10, nullable: true },
      port_pickup_datetime: { type: "datetime", nullable: true },
      warehouse_customer_id: { type: "number", nullable: true },
      warehouse_address: { type: "string", maxLength: 255, nullable: true },
      scac_code: { type: "string", maxLength: 20, nullable: true },
      seal_number: { type: "string", maxLength: 80, nullable: true },
      gate_code: { type: "string", maxLength: 80, nullable: true },
      pin_code: { type: "string", maxLength: 80, nullable: true },
      checked_in_code: { type: "string", maxLength: 80, nullable: true },
      status: { type: "enum", values: ["available", "in_transit", "delivered", "maintenance"] },
      current_location: { type: "string", maxLength: 160, nullable: true },
    },
  },
  dispatches: {
    table: "dispatches",
    orderBy: "id DESC",
    fields: {
      customer_id: { type: "number", required: true },
      driver_id: { type: "number", required: true },
      container_id: { type: "number", required: true },
      dispatch_type: { type: "string", required: true, maxLength: 50 },
      pickup_location: { type: "string", required: true, maxLength: 160 },
      pickup_address: { type: "string", required: true, maxLength: 255 },
      pickup_date: { type: "string", required: true, maxLength: 10 },
      pickup_time: { type: "string", required: true, maxLength: 8 },
      delivery_location: { type: "string", required: true, maxLength: 160 },
      delivery_address: { type: "string", required: true, maxLength: 255 },
      delivery_date: { type: "string", required: true, maxLength: 10 },
      delivery_time: { type: "string", required: true, maxLength: 8 },
      status: { type: "enum", values: ["pending", "assigned", "in_transit", "completed", "cancelled"] },
      notes: { type: "string", nullable: true },
    },
  },
};
